export enum ROUTE_NAME {
  ABOUTYOU = "../screens/Auth/AboutYou",
  EMAILVERIFICATION = "../screens/Auth/EmailVerification",
  LOGIN = "../screens/Auth/Login",
  BOTTOM_TAB = "Bottomtab",
  WHATSYOURGOAL = "../screens/Auth/WhatsYourGoal",
  GETSTARTED = "../screens/Auth/GetStarted",
  CREATEACCOUNT = "../screens/Auth/CreateAccount",
  WORKOUTTIME = "../screens/Auth/WorkoutTime",
  FITNESSPLAN = "../screens/Plan/FitnessPlan",
  FITNESS_PLAN = "Fitstack",
  BEGINNERPLAN = "../screens/Plan/BeginnerPlan",
  VIDEO = "../component/VideoLink",
  CLASSTIMER = "../component/PlanTimer",
  SUBSCRIPTION = "../component/Subscription",
  BREAKFAST = "../screens/Plan/MealPLan/Breakfast",
  FORGOTPASSWORD = "../screens/Auth/ForgotPassword",
}
